### ISSUE TITLE
Handle JS dependencies appropriately.

### ISSUE THREAD

**Issue by broesamle** [broesamle/clip_8#2]
Jasmine is the only one, at the time of writing. It is more or less copied in by hand. Version changes would require a change of `src=...` in the `script` elements.

**Comment by ioctaptceb** [comment]
I think implementing `npm` / `yarn` as a package manager will be the best way to go. `yarn` is likely better for your needs

both will allow you to set a default test command. You can do `jasmine .` there. when you initialize jasmine, it will create a spec/support folder where you can determine which files it should use and how.

**Comment by broesamle** [comment]
thanks for the quick repy!

All JS code runs client side, so I guess there is no way around checking a copy into the repo and then refer to it in the html?

```html
<link rel="shortcut icon" type="image/png" href="../js/jasmine/jasmine_favicon.png">
<link rel="stylesheet" href="../css/jasmine.css">
<script src="../js/jasmine/jasmine.js"></script>
<script src="../js/jasmine/jasmine-html.js"></script>
<script src="../js/jasmine/boot.js"></script>
```

**Comment by broesamle** [comment]
just followed the jasmine install instructions (download and place directly)

and checked it into the repo.
